---
language: ruby
before_install: gem install bundler -v '< 2.0'
script: bundle exec rspec
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-9.2.11.0
  - jruby-head
  - truffleruby
matrix:
  allow_failures:
    - rvm: jruby-9.2.11.0
    - rvm: jruby-head
    - rvm: truffleruby
  fast_finish: true
branches:
  only: master
notifications:
  email: false
